// npm install @react-navigation/bottom-tabs
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import Login from './screens/Login';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { Ionicons } from '@expo/vector-icons';
import welcomeScreen from './screens/welcomeScreen';


export default function App() {
  const Tab = createBottomTabNavigator();
// The route object provided to the screenOptions function is automatically generated by the navigation library and represents the current route
  return (
    <NavigationContainer>
      <Tab.Navigator
        screenOptions={({ route }) => ({
          tabBarIcon: ({ focused, color, size }) => {
            let iconn;
            if (route.name === 'Main Page') {
              iconn = focused ? 'home' : 'home-outline';
            } else if (route.name === 'Welcome') {
              iconn = "ios-enter"
            }
            return <Ionicons name={iconn} size={size} color={color} />;
          },
          tabBarActiveTintColor: 'tomato',
          tabBarInactiveTintColor: 'gray',  
          
        })}
        initialRouteName='Main Page'
      > 
        <Tab.Screen name="Main Page" component={Login} />
        <Tab.Screen name="Welcome" component={welcomeScreen} /> 
      </Tab.Navigator>
    </NavigationContainer>
  );
}
